# Generated by Django 5.2.10 on 2026-01-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_remove_blogpost_excerpt_remove_blogpost_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
