# Generated by Django 5.2.10 on 2026-01-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0005_notice_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='snippet',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
