# Generated by Django 5.2.10 on 2026-01-28 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0007_alter_blogpost_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
