# Generated by Django 5.2.10 on 2026-01-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0008_remove_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={},
        ),
    ]
