# Generated by Django 5.2.10 on 2026-01-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0010_rename_title_notice_headline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='how_to_apply',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='organization_details',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
