# Generated by Django 5.2.10 on 2026-01-31 12:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0011_vacancy_how_to_apply_vacancy_organization_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='how_to_apply',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
