# Generated by Django 5.2.10 on 2026-01-31 12:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0012_alter_vacancy_how_to_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='contact_details',
            field=ckeditor.fields.RichTextField(default=11),
            preserve_default=False,
        ),
    ]
