# Generated by Django 5.2.10 on 2026-03-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0014_notice_author_vacancy_author_alter_story_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='failed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='sent_count',
            field=models.IntegerField(default=0),
        ),
    ]
