---
deployment:
  tasks:
    # ==========================================================================
    # IMPORTANT: REPLACE 'ngodiges' WITH YOUR ACTUAL cPanel USERNAME
    # ==========================================================================
    - export DEPLOYPATH=/home/ngodiges/public_html/NGO-News-Digest/
    
    # ==========================================================================
    # Copy all files from the git repository to the deployment directory
    # ==========================================================================
    - /bin/cp -r * $DEPLOYPATH
    - /bin/cp -r .[!.]* $DEPLOYPATH 2>/dev/null || :
    
    # ==========================================================================
    # Set up Python environment
    # ==========================================================================
    - cd $DEPLOYPATH
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - python manage.py migrate --noinput
    - python manage.py collectstatic --noinput
    
    
    # ==========================================================================
    # Fix permissions
    # ==========================================================================
    - chmod 755 $DEPLOYPATH
    - chmod 644 $DEPLOYPATH/passenger_wsgi.py