# Generated by Django 5.2.10 on 2026-01-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='token',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='verification_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
