# Generated by Django 5.2.10 on 2026-01-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_facebook_user_twitter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='intrests',
            new_name='interests',
        ),
    ]
