# Generated by Django 5.2.10 on 2026-01-29 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_intrests_user_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='instagram_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='jobs_listed',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='organization_name',
            field=models.CharField(default='NGO News Digest', max_length=200),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='partner_categories',
            field=models.TextField(blank=True, default='UN Agencies,International NGOs,Local NGOs,Government Ministries,Development Partners,Private Sector'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='partner_ngos_count',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='sectors_covered',
            field=models.TextField(blank=True, default='Health & WASH,Agriculture & Food Security,Education & Skills Development,Livelihoods & Economic Empowerment,Gender & Protection,Climate Resilience,Governance & Accountability,Humanitarian Response,Youth & Child Development,Disability Inclusion'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='service_1_description',
            field=models.TextField(blank=True, default="Document and share success stories that showcase the tangible impact of NGO work across Zimbabwe's communities."),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='service_1_title',
            field=models.CharField(blank=True, default='Impact Storytelling', max_length=100),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='service_2_description',
            field=models.TextField(blank=True, default="Connect talented professionals with meaningful opportunities in Zimbabwe's civil society sector through our job portal."),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='service_2_title',
            field=models.CharField(blank=True, default='Career Hub', max_length=100),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='service_3_description',
            field=models.TextField(blank=True, default='Disseminate important announcements, funding opportunities, events, and policy updates affecting the NGO sector.'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='service_3_title',
            field=models.CharField(blank=True, default='Notice Board', max_length=100),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='service_4_description',
            field=models.TextField(blank=True, default='Facilitate connections and collaboration between NGOs, donors, government agencies, and communities.'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='service_4_title',
            field=models.CharField(blank=True, default='Sector Networking', max_length=100),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='show_partners',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='show_statistics',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='show_team_preview',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='stories_published',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='subscribers_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='tagline',
            field=models.CharField(default='Amplifying Civil Society Impact in Zimbabwe', max_length=300),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='value_1_description',
            field=models.TextField(blank=True, default='We maintain the highest standards of accuracy, transparency, and ethical reporting in all our coverage.'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='value_1_title',
            field=models.CharField(blank=True, default='Integrity', max_length=100),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='value_2_description',
            field=models.TextField(blank=True, default='We amplify diverse voices and ensure representation across all provinces and community groups in Zimbabwe.'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='value_2_title',
            field=models.CharField(blank=True, default='Inclusivity', max_length=100),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='value_3_description',
            field=models.TextField(blank=True, default='We prioritize stories and information that demonstrate measurable change and development outcomes.'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='value_3_title',
            field=models.CharField(blank=True, default='Impact-Focused', max_length=100),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='value_4_description',
            field=models.TextField(blank=True, default='We embrace new approaches to storytelling and information sharing that increase engagement and accessibility.'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='value_4_title',
            field=models.CharField(blank=True, default='Innovation', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='about_us',
            field=models.TextField(blank=True, default='NGO News Digest is a Zimbabwe-based news and media initiative dedicated to sharing, amplifying, and celebrating the work of non-governmental organisations operating across Zimbabwe.'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='address',
            field=models.TextField(blank=True, default='123 Development Avenue, Harare, Zimbabwe'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='contact_email',
            field=models.EmailField(blank=True, default='contact@ngonewsdigest.co.zw', max_length=254),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='contact_phone',
            field=models.CharField(blank=True, default='+263 77 123 4567', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://facebook.com/ngonewsdigest'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='linkedin_url',
            field=models.URLField(blank=True, default='https://linkedin.com/company/ngonewsdigest'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='mission',
            field=models.TextField(blank=True, default='To document, share, and elevate the work of NGOs in Zimbabwe through timely, impactful, and comprehensive coverage that connects grassroots initiatives with national development goals.'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='twitter_url',
            field=models.URLField(blank=True, default='https://twitter.com/ngonewsdigest'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='vision',
            field=models.TextField(blank=True, default="To be Zimbabwe's premier platform for celebrating and amplifying civil society impact, serving as the definitive repository of positive change and development innovation."),
        ),
    ]
