# Generated by Django 5.2.10 on 2026-01-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_siteinfo_instagram_url_siteinfo_jobs_listed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='jobs_listed',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='partner_ngos_count',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='stories_published',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='subscribers_count',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='value_1_description',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='value_1_title',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='value_2_description',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='value_2_title',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='value_3_description',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='value_3_title',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='value_4_description',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='value_4_title',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='values',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
