# Generated by Django 5.2.10 on 2026-01-30 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_siteinfo_jobs_listed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteinfo',
            old_name='partner_categories',
            new_name='partners',
        ),
    ]
