# Generated by Django 5.2.10 on 2026-01-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_partner_categories_siteinfo_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='youtube_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
