# Generated by Django 5.2.10 on 2026-01-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_siteinfo_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='head_shot',
            field=models.ImageField(blank=True, null=True, upload_to='team_head_shots/'),
        ),
    ]
