# Generated by Django 5.2.10 on 2026-01-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_teammember_head_shot'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='prefix',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
