# Generated by Django 5.2.10 on 2026-01-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_siteinfo_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='logo',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicons/'),
        ),
    ]
