# Generated by Django 5.2.10 on 2026-01-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_siteinfo_logo_siteinfo_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='company_logo',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='favicon',
            field=models.URLField(blank=True, default=''),
        ),
    ]
