# Generated by Django 5.2.10 on 2026-01-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_siteinfo_company_logo_alter_siteinfo_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='department',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='location',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(max_length=30),
        ),
    ]
