# Generated by Django 5.2.10 on 2026-02-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_user_roles_user_role_alter_teammember_prefix_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='roles',
        ),
    ]
